### ISSUE TITLE
Writing to CSV

### ISSUE THREAD

**Issue by shawnanctil** [woosmap/samples#1]
I'm encountering a few issues relating to writing to CSV.
Namely:

- The program writes the first 56 results to the csv file and then stops.
- It writes the entire result into the first cell (and so I can split by delimiter) but it also writes some parts of the results (but not all) in adjacent cells.

I'm wondering if some of the changes I've made to the code are responsible for this? Any help you can provide would be appreciated.

My top-level parameters are here:

```
ADDRESS_COLUMNS_NAME = ["member","campus","street","city","province","country"]
COMPONENT_RESTRICTIONS_COLUMNS_NAME = {}
NEW_COLUMNS_NAME = ["Lat", "Long", "Error", "formatted_address", "location_type"]
DELIMITER = ";"
RETRY_COUNTER_CONST = 5

dir = os.path.dirname(__file__)
INPUT_CSV_FILE = os.path.join(dir, "./member_info.csv")
OUTPUT_CSV_FILE = os.path.join(dir, "geo_members.csv")
```

I added a timeout parameter to the GoogleV3 call:

```
    geo_locator = GoogleV3(api_key=GOOGLE_API_KEY,
                           client_id=GOOGLE_CLIENT_ID,
                           secret_key=GOOGLE_SECRET_KEY,timeout=10)
```

I've also made some changes to a few sections to allow for French characters (the program was repeatedly breaking when it encountered non-English chars.

**Line 106 - 109:**

```
                for column_name in NEW_COLUMNS_NAME:
                    try:
                        if isinstance(location[column_name], str):
                            temp_row.append(location[column_name].encode("latin-1"))
```

**Line 156 - 159**

```
    print("address line     : %s" % line_address)
    print("geocoded address : %s" % location_result["formatted_address"].encode('latin-1','replace'))
    print("location type    : %s" % location_result["location_type"].encode('latin-1','replace'))
    print("coordinates      : %s, %s" % (location_result["Lat"],location_result["Long"]))
```

Would be great to get some clarification as to how I broke your program.

**Comment by gaelsimon** [comment]
Hi,
Are you able to share your source CSV file (member_info.csv)?
Could you post the output error or does the script just stop without any output?

**Comment by shawnanctil** [comment]
[member_info.xlsx](https://github.com/woosmap/samples/files/1685945/member_info.xlsx)

I can't upload the csv file apparently, but here's an Excel version.

I'm not getting any error messages in regards to writing to the output file. I've run the script a few times and it just stops writing after line 56.

That said, I did get a UnicodeError in the console after the script was finished running (i.e. after it printed all the results to the console). I've encountered a few Unicode errors as I was modifying the script, hence all the "latin-1" encoding lines. Not sure if that's the source of my issues, but it was the only way I could get the script to run with French character inputs.

Hope this helps, and thanks for responding.

**Comment by gaelsimon** [comment]
We've updated the script and moved to [this repository](https://github.com/woosmap/geopy-googlemaps-batchgeocoder).
I've geocoded your file and all the rows are well processed.

here is your original file converted to CSV : 
[member_info.csv.zip](https://github.com/woosmap/woosmap-samples/files/4138143/member_info.csv.zip)

and the the file with geocoded addresses :
[member_info_processed.csv.zip](https://github.com/woosmap/woosmap-samples/files/4138147/member_info_processed.csv.zip)
